def main():
    application = Application.builder().token(BOT_TOKEN).build()
    
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("access", access_command))
    application.add_handler(CommandHandler("vehicle", vehicle_command))
    application.add_handler(CommandHandler("num", num_command))
    application.add_handler(CommandHandler("aadhar", aadhar_command))
    application.add_handler(CommandHandler("pan", pan_command))
    application.add_handler(CommandHandler("upi", upi_command))
    application.add_handler(CallbackQueryHandler(menu_handler))
    
    print("🤖 Bot is starting...")
    print("✅ All commands loaded successfully")
    print("Commands: /start, /access, /vehicle, /num, /aadhar, /pan, /upi")
    print("\n🚗 Vehicle Search:")
    print("   - API: https://chuchirandiki.vercel.app/api/vehicle?reg_no=XXXXXXXXXX")
    print("   - Usage: /vehicle MH47BG7036")
    print("\n📱 Mobile Search:")
    print("   - API: https://raxxosint.onrender.com/leakosint?key=MRX&quiry=+919873534030")
    print("   - Usage: /num +919873534030")
    print("   - Shows: ALL fields from ALL records")
    print("\n🪪 Aadhaar Search:")
    print("   - API: https://raxxosint.onrender.com/leakosint?key=MRX&quiry=XXXXXXXXXX")
    print("   - Usage: /aadhar 691631435425")
    print("   - Shows: ALL fields from ALL records")
    print("\n📇 PAN Search:")
    print("   - Usage: /pan ACCPA2495F")
    print("\n💳 UPI Validation:")
    print("   - Usage: /upi vipansharma1931141@okhdfcbank")
    print("\n🔒 All API endpoints and keys are hidden from users")
    print("\n✅ Bot is ready!")
    application.run_polling(allowed_updates=Update.ALL_TYPES)
